# Gemfile to help setting up the initial development environment
source 'https://rubygems.org'

gem 'appium_console'
gem 'appium_lib'
gem 'rake'
gem 'cpf_cnpj'
gem 'cucumber'
gem 'cuke_linter'
gem 'faker'
gem 'parallel_tests'
gem 'json'
gem 'pry'
gem 'report_builder'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'tty-command'
gem 'xcpretty'
gem 'allure-cucumber'
gem 'byebug', require: false 
gem 'percentage'
gem 'documentos_br'
gem 'open3'
gem 'rexml'
gem 'net-sftp'
gem 'rspec-expectations'
gem 'rspec-core'
gem 'savon'
gem 'touch_action'
gem 'activesupport'
gem 'os'
gem 'idevice'
gem 'cpf_faker'
gem 'excon'
#gem 'httparty'